---
# Consolidated Ansible Galaxy Dependencies
# Merged from ansible-playbooks, mac-dev-playbook, and infra requirements

collections:
  # General community modules (used across all playbooks)
  - name: community.general
    version: ">=3.0.0"

  # macOS-specific collection (for Mac playbooks)
  - name: geerlingguy.mac

roles:
  # macOS roles (used by playbooks/mac/*.yml)
  - name: elliotweiser.osx-command-line-tools
