---
# External Ansible Galaxy role dependencies

collections:
  - name: community.general
    version: ">=3.0.0"

roles: []
  # Add external role dependencies here as needed
  # Example:
  # - name: geerlingguy.homebrew
  #   version: "4.2.0"
